# ATTENTION: if you're copying this you'll need to change the paths

[consensus]
checkpoint_sync = true

[mempool]
eviction_memory_time = "1h"
tx_cost_limit = 80000000
debug_enable_at_height = 0

[metrics]

[mining]
# miner_address = 'tmMpyskoGLoY1VCagDpEXe5ubNcpHFYypum'
# miner_address = 'tmDdbVDgBonrM2XRyyCqjAuX97Xs6TEtVLg'
miner_address = 'tmA3HnFoW2EnLU648vntmGuaVMUWBrxSmkz' # Regtest
internal_miner = true


[network]
cache_dir = true
crawl_new_peer_interval = "1m 1s"
initial_mainnet_peers = [
    "dnsseed.z.cash:8233",
    "dnsseed.str4d.xyz:8233",
    "mainnet.seeder.zfnd.org:8233",
    "mainnet.is.yolo.money:8233",
]
initial_testnet_peers = ["80.78.31.51:8233", "80.78.31.32:8233"]

listen_addr = "0.0.0.0:8233"
max_connections_per_ip = 1
peerset_initial_target_size = 25
network = "Testnet"

[network.testnet_parameters]
network_magic = [67, 108, 84, 110] # ClTn = Crosslink Testnet
slow_start_interval = 0

[network.testnet_parameters.activation_heights]
NU6 = 1

[rpc]
cookie_dir = "./cookie-dir/zebra_sl4" # ****
debug_force_finished_sync = false
enable_cookie_auth = false
parallel_cpu_threads = 0
listen_addr = '127.0.0.1:8232'

[state]
cache_dir = "./cache-dir/zebra_sl4" # *****
delete_old_database = true
ephemeral = true

[sync]
checkpoint_verify_concurrency_limit = 1000
download_concurrency_limit = 50
full_verify_concurrency_limit = 20
parallel_cpu_threads = 0

[tracing]
buffer_limit = 128000
force_use_color = false
use_color = true
use_journald = false

[crosslink]
insecure_user_name = "127.0.0.1:8233"
malachite_peers = ["127.0.0.1:8233"]
do_not_manipulate_config = true
