# ATTENTION: if you're copying this you'll need to change the paths

[consensus]
checkpoint_sync = true

[mempool]
eviction_memory_time = "1h"
tx_cost_limit = 80000000
debug_enable_at_height = 0

[metrics]

[mining]
# account id 0
miner_address = 'tmRB9AEVsxNAQsqtJPqJUje9KCaAijpS77z'
# account id 1 (as set up by wallet)
# miner_address = "tmMusggSMq97LU2g3XUysVeW8mtXj2HZNV3"
internal_miner = true


[network]
cache_dir = true
crawl_new_peer_interval = "1m 1s"
initial_mainnet_peers = [
    "dnsseed.z.cash:8233",
    "dnsseed.str4d.xyz:8233",
    "mainnet.seeder.zfnd.org:8233",
    "mainnet.is.yolo.money:8233",
]
initial_testnet_peers = [
#    "dnsseed.testnet.z.cash:18233",
#    "testnet.seeder.zfnd.org:18233",
#    "testnet.is.yolo.money:18233",
    "70.34.201.202:8233",
    "45.76.30.90:8233",
    "127.0.0.1:8235",
]
listen_addr = "0.0.0.0:8233"
max_connections_per_ip = 10
network = "Testnet"
peerset_initial_target_size = 25

[network.testnet_parameters]
network_magic = [67, 108, 84, 110] # ClTn = Crosslink Testnet
slow_start_interval = 0

[network.testnet_parameters.activation_heights]
NU6 = 1

[rpc]
cookie_dir = "/Users/sam/Library/Caches/zebra_multiplayer/peer0"
debug_force_finished_sync = false
enable_cookie_auth = false
parallel_cpu_threads = 0
listen_addr = '127.0.0.1:8232'

[state]
cache_dir = "/Users/sam/Library/Caches/zebra_multiplayer/peer0"
delete_old_database = true

[sync]
checkpoint_verify_concurrency_limit = 1000
download_concurrency_limit = 50
full_verify_concurrency_limit = 20
parallel_cpu_threads = 0

[tracing]
buffer_limit = 128000
force_use_color = false
use_color = true
use_journald = false


[crosslink]
do_not_manipulate_config = true
i_am_the_unstaker = true
listen_address = "127.0.0.1:24834"
public_address = "127.0.0.1:24834"
bft_peers = [
"127.0.0.1:24834",
"127.0.0.1:24835",
]
