
[network.testnet_parameters]
slow_start_interval = 0
network_magic = [67, 108, 82, 110] # ClRn = Crosslink Regestnet

[consensus]
checkpoint_sync = false

[crosslink]
listen_address = "127.0.0.1:38234"
public_address = "127.0.0.1:38234"
do_not_manipulate_config = true
malachite_peers = [
	"127.0.0.1:28234",
	"127.0.0.1:38234",
]

[mempool]
eviction_memory_time = "1h"
tx_cost_limit = 80000000

debug_enable_at_height = 1

[metrics]

[mining]
miner_address = 'tmRB9AEVsxNAQsqtJPqJUje9KCaAijpS77z'
internal_miner = true

[network]
cache_dir = true
crawl_new_peer_interval = "1m 1s"
initial_mainnet_peers = [
    "dnsseed.z.cash:8233",
    "dnsseed.str4d.xyz:8233",
    "mainnet.seeder.zfnd.org:8233",
    "mainnet.is.yolo.money:8233",
]
initial_testnet_peers = [
	"127.0.0.1:28233",
	"127.0.0.1:38233",
]
listen_addr = "[::]:38233"
max_connections_per_ip = 100
network = "Testnet"
peerset_initial_target_size = 25

[rpc]
cookie_dir = "C:/Users/azmre/AppData/Local/zebra_regtestnet_2"
debug_force_finished_sync = false
enable_cookie_auth = false
parallel_cpu_threads = 0
listen_addr = "127.0.0.1:38232"

[state]
cache_dir = "C:/Users/azmre/AppData/Local/zebra_regtestnet_2"
delete_old_database = true
ephemeral = false

[sync]
checkpoint_verify_concurrency_limit = 1000
download_concurrency_limit = 50
full_verify_concurrency_limit = 20
parallel_cpu_threads = 0

[tracing]
buffer_limit = 128000
force_use_color = false
use_color = true
use_journald = false

