[package]
name = "zaino-proto"
description = "Holds tonic files and build logic for the lightwallet and darkside RPCs."
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[dependencies]
# Miscellaneous Workspace
tonic = { workspace = true }
prost = { workspace = true }
tonic-prost = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
tonic-prost-build = { workspace = true }
which = { workspace = true }
sha2 = "0.10.9"
walkdir = "2.5.0"
